### ISSUE TITLE
missing function: madvise when using ffmpeg-all-codecs.js -c:v libx264

### ISSUE THREAD

**Issue by SpokenBanana** [bgrins/videoconverter.js#34]
The command arguments I'm using are: 

arguments: ['-t','1', '-ss',startTime.toString(), '-i',  'name.mp4', '-vf', 'showinfo',   '-strict',
           '-2', '-c:v', 'libx264', 'output.mp4'],

my worker.js is importing ffmpeg-all-codec.js 

output says its missing the function madvise (at the bottom)

output:

[h264 @ 0xee09b0] Warning: not compiled with thread support, using thread emulation

[aac @ 0xedf280] Warning: not compiled with thread support, using thread emulation

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'WIN_20151010_193627.MP4':

  Metadata:

```
major_brand     : mp42

minor_version   : 0

compatible_brands: mp41isom

creation_time   : 2015-10-10 23:36:28
```

  Duration: 00:00:03.32, start: 0.000000, bitrate: 5484 kb/s

```
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], 5328 kb/s, 15.09 fps, 14.92 tbr, 30k tbn, 60 tbc (default)

Metadata:

  creation_time   : 2015-10-10 23:36:28

  handler_name    : VideoHandler

Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 161 kb/s (default)

Metadata:

  creation_time   : 2015-10-10 23:36:28

  handler_name    : SoundHandler
```

No pixel format specified, yuvj420p for H.264 encoding chosen.

Use -pix_fmt yuv420p for compatibility with outdated media players.

[libx264 @ 0xed9740] Warning: not compiled with thread support, using thread emulation

[libx264 @ 0xed9740] using SAR=1/1

[libx264 @ 0xed9740] using cpu capabilities: none!

missing function: madvise
-1
-1
ffmpeg-all-codecs.js:65913 Uncaught abort() at Error
    at stackTrace (~/scripts/ffmpeg-all-codecs.js:1082:15)
    at abort (~/scripts/ffmpeg-all-codecs.js:65997:25)
    at _madvise (~/scripts/ffmpeg-all-codecs.js:62870:52)
    at MLb (~/scripts/ffmpeg-all-codecs.js:64078:1057420)
    at ULb (~/scripts/ffmpeg-all-codecs.js:64078:1073603)
    at Array.cPa (~/scripts/ffmpeg-all-codecs.js:64086:238174)
    at _4a (~/scripts/ffmpeg-all-codecs.js:64098:652222)
    at Qh (~/scripts/ffmpeg-all-codecs.js:64070:157892)
    at Object.Nh [as _main](~/scripts/ffmpeg-all-codecs.js:64070:138227)
    at Object.callMain (~/scripts/ffmpeg-all-codecs.js:65894:

same thing appears to happen even without the -c:v libx264 arguments. Any help?

**Comment by gfwilliams** [comment]
I don't know if this helps, but I'm finding it seems to be to do with the video dimensions in my case. If I make it 320x240 everything works, but other widths seem to break.

**Comment by bgrins** [comment]
I think I've seen that before too, but wasn't able to track it down

**Comment by danschumann** [comment]
I just commented out the _madvise function inside of ffmpeg-all-codecs.js

All it did was print a warning and then abort.  So, NO MORE ABORT!

My video compiles fine.

**Comment by indianakernick** [comment]
@danschumann yeah that's what i did. Worked fine ever since

**Comment by harryfear** [comment]
I had the same problem with this command:

`-loop 1 -i input.jpeg -c:v libx264 -t 1 -pix_fmt yuv420p output.mp4`
([from docs - i.e. single image to slideshow](https://trac.ffmpeg.org/wiki/Slideshow#Singleimage))

Commenting out the contents of the madvise function app worked.
